import type { Project, Task, User, Client } from "@/types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john@example.com",
    avatar: "/placeholder.svg?height=32&width=32",
    role: "Developer",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    avatar: "/placeholder.svg?height=32&width=32",
    role: "Designer",
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike@example.com",
    avatar: "/placeholder.svg?height=32&width=32",
    role: "Project Manager",
  },
  {
    id: "4",
    name: "Sarah Wilson",
    email: "sarah@example.com",
    avatar: "/placeholder.svg?height=32&width=32",
    role: "QA Engineer",
  },
]

export const mockClients: Client[] = [
  {
    id: "1",
    name: "TechCorp Inc.",
    email: "contact@techcorp.com",
    avatar: "/placeholder.svg?height=32&width=32",
    company: "TechCorp Inc.",
    projects: ["1", "3"],
    createdAt: "2024-01-01",
  },
  {
    id: "2",
    name: "FinanceBank",
    email: "info@financebank.com",
    avatar: "/placeholder.svg?height=32&width=32",
    company: "FinanceBank Ltd.",
    projects: ["2"],
    createdAt: "2024-01-15",
  },
]

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "E-commerce Platform",
    description: "Modern e-commerce platform with advanced features",
    client: {
      name: "TechCorp Inc.",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    status: "active",
    deadline: "2024-02-15",
    gitIntegration: true,
    progress: 75,
    teamMembers: [mockUsers[0], mockUsers[1], mockUsers[2]],
    createdAt: "2024-01-01",
  },
  {
    id: "2",
    name: "Mobile Banking App",
    description: "Secure mobile banking application",
    client: {
      name: "FinanceBank",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    status: "active",
    deadline: "2024-03-01",
    gitIntegration: true,
    progress: 45,
    teamMembers: [mockUsers[1], mockUsers[3]],
    createdAt: "2024-01-10",
  },
  {
    id: "3",
    name: "CRM System",
    description: "Customer relationship management system",
    client: {
      name: "TechCorp Inc.",
      avatar: "/placeholder.svg?height=32&width=32",
    },
    status: "planning",
    deadline: "2024-04-01",
    gitIntegration: false,
    progress: 15,
    teamMembers: [mockUsers[0], mockUsers[2]],
    createdAt: "2024-01-20",
  },
]

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Design user authentication flow",
    description: "Create wireframes and mockups for the login and signup process",
    status: "in-progress",
    priority: "high",
    assignee: mockUsers[0],
    dueDate: "2024-01-15",
    projectId: "1",
    checklist: [
      { id: "1", text: "Create wireframes", completed: true },
      { id: "2", text: "Design mockups", completed: false },
      { id: "3", text: "User testing", completed: false },
    ],
    attachments: [],
    gitBranch: "feature/auth-flow",
    whatsappLogs: [
      {
        id: "1",
        message: "Task assigned to you",
        timestamp: "2024-01-10T10:00:00Z",
        sender: "System",
        status: "delivered",
      },
    ],
    createdAt: "2024-01-10",
    updatedAt: "2024-01-12",
  },
  {
    id: "2",
    title: "Implement API endpoints",
    description: "Build REST API for user management",
    status: "todo",
    priority: "medium",
    assignee: mockUsers[1],
    dueDate: "2024-01-20",
    projectId: "1",
    checklist: [
      { id: "4", text: "Setup database schema", completed: false },
      { id: "5", text: "Create user endpoints", completed: false },
    ],
    attachments: [],
    whatsappLogs: [],
    createdAt: "2024-01-11",
    updatedAt: "2024-01-11",
  },
  {
    id: "3",
    title: "Setup CI/CD pipeline",
    description: "Configure automated deployment pipeline",
    status: "backlog",
    priority: "low",
    assignee: mockUsers[2],
    dueDate: "2024-01-25",
    projectId: "1",
    checklist: [],
    attachments: [],
    whatsappLogs: [],
    createdAt: "2024-01-12",
    updatedAt: "2024-01-12",
  },
  {
    id: "4",
    title: "Mobile app testing",
    description: "Comprehensive testing of mobile banking features",
    status: "review",
    priority: "urgent",
    assignee: mockUsers[3],
    dueDate: "2024-01-18",
    projectId: "2",
    checklist: [
      { id: "6", text: "Functional testing", completed: true },
      { id: "7", text: "Security testing", completed: false },
    ],
    attachments: [],
    whatsappLogs: [],
    createdAt: "2024-01-13",
    updatedAt: "2024-01-14",
  },
  {
    id: "5",
    title: "Database optimization",
    description: "Optimize database queries for better performance",
    status: "done",
    priority: "medium",
    assignee: mockUsers[0],
    dueDate: "2024-01-12",
    projectId: "2",
    checklist: [
      { id: "8", text: "Analyze slow queries", completed: true },
      { id: "9", text: "Add indexes", completed: true },
    ],
    attachments: [],
    whatsappLogs: [],
    createdAt: "2024-01-08",
    updatedAt: "2024-01-12",
  },
]
